# Config to connect to repository
backend:
  name: bitbucket
  branch: master
  repo: misfitwearablesinc/portfolio-cms

# Folder to upload file media: photos, assets,... 
media_folder: static/assets

# List of languages
collections:
  # English
  - name: EnPost
    label: English Post
    folder: /src/pages/post
    create: true
    slug: "{{url}}"
    extension: "en.md"
    format: "frontmatter"
    fields:
      - { name: url, label: URL (One post in different languages must have same url) }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  # Japanese
  - name: JaPost
    label: Japanese Post
    folder: /src/pages/post
    create: true
    slug: "{{url}}"
    extension: "ja.md"
    format: "frontmatter"
    fields:
      - { name: url, label: URL (One post in different languages must have same url) }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  # Portugal
  - name: PtPost
    label: Portugal Post
    folder: /src/pages/post
    create: true
    slug: "{{url}}"
    extension: "pt.md"
    format: "frontmatter"
    fields:
      - { name: url, label: URL (One post in different languages must have same url) }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  # Vietnamese
  - name: ViPost
    label: Vietnamese Post
    folder: /src/pages/post
    create: true
    slug: "{{url}}"
    extension: "vi.md"
    format: "frontmatter"
    fields:
      - { name: url, label: URL (One post in different languages must have same url) }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }