backend:
  name: github
  branch: master
  repo: ntloi95/gatsby-tips

media_folder: static/assets

slug:
  encoding: "ascii"
  clean_accents: false

collections:
  - name: post
    label: Post
    folder: /src/pages/post
    create: true
    slug: "{{url}}.{{language}}"
    fields:
      - { name: url, label: URL }
      - { name: language, label: Language }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }