backend:
  name: github
  branch: master
  repo: ntloi95/gatsby-tips

media_folder: static/assets

collections:
  - name: post
    label: Post
    folder: /src/pages/post
    create: true
    fields:
      - { name: slug, label: Filename }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }